server:
  port: 8082

spring:
    application:
        name: activityFlow
    jackson:
        serialization:
            indent_output: true
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    #数据库连接
    datasource:
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/yue?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
            jdbc-url: jdbc:mysql://127.0.0.1:3306/yue?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
            username: root
            password:
            initial-size: 3
            max-active: 20
            druid.min-idle: 5
            # 监控配置项
            stat-view-servlet:
                enabled: true
                reset-enable: true
                url-pattern: /druid/*
                # allow: 127.0.0.1
                login-username: newtv
                login-password: supernewtv
            filter:
                wall:
                  enabled: true
                  db-type: mysql
                  log-violation: true
                  throw-exception: true
    activiti:
      #activity启动时不检查流程配置，processes目录
      check-process-definitions: false
      #false：false为默认值，设置为该值后，Activiti在启动时，会对比数据库表中保存的版本，如果版本不匹配时，将在启动时抛出异常。
      #true：设置为该值后，Activiti会对数据库中所有的表进行更新，如果表不存在，则Activiti会自动创建。
      #create-drop：Activiti启动时，会执行数据库表的创建操作，在Activiti关闭时，执行数据库表的删除操作。
      #drop-create：Activiti启动时，执行数据库表的删除操作在Activiti关闭时，会执行数据库表的创建操作。
      database-schema-update: true
      #none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
      #activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
      #audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
      #full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
      history-level: full
    #thymeleaf关闭缓存
    thymeleaf:
      cache: false
#    jpa:
#      show-sql: true
#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.activityFlow.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  #mapper-locations: com.newtv.piper.core.dao.mapper
mapper:
  style: normal
  mappers: com.activityFlow.repository.TKMapper
  identity: MYSQL